version: "3.9"
services:
  dilly-dalle-sd:
    container_name: "dilly-dalle-sd-bot"
    build: .
    restart: always
    environment:
    - "LOGLEVEL=DEBUG" # DEBUG, INFO, WARNING, ERROR, CRITICAL
    - "TELEGRAM_BOT_TOKEN="
    - "STABLE_DIFFUSION_URL="
    - "DATABASE_URL=/app/data/sqlite/dilly-dalle-sd.db" # Only modify if you want different volume mappings. If you change the filename update entrypoint.sh
    volumes:
      - ./data:/app/data # sqlite db and generated images